#:schema node_modules/wrangler/config-schema.json
name = "meangirlsoct3"
main = "src/index.js"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]


[ai]
binding = "AI"

[build.upload]
format = "modules"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

[build.upload.rules.exclude]
paths = ["webm-muxer"]